
substitutions:
  device_name: <<Device Name>>
  device_description: <<Device Description>>
  friendly_name: <<Device friendly Name>>

esphome:
  name: ${device_name}
  comment: ${device_description}
  platform: ESP8266
  board: esp01_1m

wifi:
  ssid: !secret wifi_ssid
  password: !secret wifi_password
  domain: !secret wifi_domain
  fast_connect: on #we only have one WiFi AP so just use the first one that matches
  ap: #since we listed an SSID above, this AP mode will only enable if no WiFi connection could be made
    ssid: !secret ap_ssid
    password: !secret ap_password

captive_portal:

# Enable logging
logger:
  baud_rate: 0 #disable UART logging since we aren't connected to GPIO1 TX

# Enable Home Assistant API
api:

# Enable OTA updates
ota:

# Enable web server
web_server:
  port: 80

# Tuya dimmer requires the UART component
uart:
  tx_pin: GPIO1
  rx_pin: GPIO3
  baud_rate: 9600
  
# Register the Tuya MCU connection
tuya:

# Tuya Dimmer Light Setup
light:
  - platform: "tuya"
    name: ${friendly_name} Dimmer
    dimmer_datapoint: 2
    switch_datapoint: 1
    min_value: 150
    max_value: 1000
    
binary_sensor:
# Reports if this device is Connected or not
  - platform: status
    name: ${friendly_name} Status
    
sensor:
# Reports the WiFi signal strength
  - platform: wifi_signal
    name: ${friendly_name} Signal
    update_interval: 60s

# Reports how long the device has been powered (in hours)
  - platform: uptime
    name: ${friendly_name} Uptime
    filters:
      - lambda: return x / 3600.0;
    unit_of_measurement: hours

text_sensor:
# Reports the ESPHome Version with compile date
  - platform: version
    name: ${friendly_name} Version

switch:
  #Switch to restart device
  - platform: restart
    name: ${friendly_name} Restart
